// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using aspnetzabota.Admin.Database.Context;

namespace aspnetzabota.Web.Migrations
{
    [DbContext(typeof(AdminContext))]
    [Migration("20191230070800_Auth")]
    partial class Auth
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("aspnetzabota.Admin.Database.Entities.Identities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Login");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("Identities");
                });

            modelBuilder.Entity("aspnetzabota.Admin.Database.Entities.Jwts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset?>("Deleted");

                    b.Property<int?>("DeletedById");

                    b.Property<DateTimeOffset>("Expires");

                    b.Property<int>("IdentityId");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTimeOffset>("Issued");

                    b.Property<string>("Token");

                    b.HasKey("Id");

                    b.HasIndex("DeletedById");

                    b.HasIndex("IdentityId");

                    b.ToTable("Jwts");
                });

            modelBuilder.Entity("aspnetzabota.Admin.Database.Entities.Jwts", b =>
                {
                    b.HasOne("aspnetzabota.Admin.Database.Entities.Identities", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById");

                    b.HasOne("aspnetzabota.Admin.Database.Entities.Identities", "Identity")
                        .WithMany()
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
